Dim swApp As Object
Sub main()

    Set swApp = Application.SldWorks   '将swApp变量设置成为SW应用程序对象
    
    Dim swModel As SldWorks.ModelDoc2    '声明对象swModel  文档对象
    
    Set swModel = swApp.ActiveDoc     '赋值
    
    If Not swModel Is Nothing Then      '如果打开模型的话，进入下一步
        
        Dim swFeat As SldWorks.Feature      '定义 sw特征变量
        Set swFeat = swModel.SelectionManager.GetSelectedObject6(1, -1)    '赋值  将xxx 特征值赋值给定义变量
        
        If Not swFeat Is Nothing Then      '选择模型的特征的话，进入下一步
            
            If swFeat.GetTypeName2() = "CoordSys" Then   '选择特征里面  坐标系的话就可以进行下一步
                
                Dim swCoordSys As SldWorks.CoordinateSystemFeatureData    '定义
                
                Set swCoordSys = swFeat.GetDefinition                  '赋值定义的坐标系信息
                Dim swMathTransform As SldWorks.MathTransform         '定义坐标转换使用的函数
                Set swMathTransform = swCoordSys.Transform            '将定义的坐标系信息传入转换函数里面
                
                Dim vMatrix As Variant                           '定义数据接收容器
                vMatrix = swMathTransform.ArrayData       '计算并赋值
                
                Debug.Print vMatrix(0) & "," & vMatrix(1) & "," & vMatrix(2) & "," & vMatrix(9) & ","
                Debug.Print vMatrix(3) & "," & vMatrix(4) & "," & vMatrix(5) & "," & vMatrix(10) & ","
                Debug.Print vMatrix(6) & "," & vMatrix(7) & "," & vMatrix(8) & "," & vMatrix(11) & ","
                Debug.Print vMatrix(13) & "," & vMatrix(14) & "," & vMatrix(15) & "," & vMatrix(12)     '打印函数计算的参数值，也就是容器内数据
                
            Else
                MsgBox "Selected feature is not a coordinate system"     'MsgBox 弹出消息：选择特征不是坐标系
            End If
        Else
            MsgBox "Please select coordinate system feature"         '弹出消息：   请选择坐标系特征
        End If
        
    Else
        MsgBox "Please open model"     '消息：  请打开模型
    End If
    
End Sub